### ISSUE TITLE
Rare panic in main.humanizeDurationSeconds

### ISSUE THREAD

**Issue by adidenko** [wayfair-incubator/minigun#74]
## Description

Got a panic from Pod when running benchmark as k8s Job. It looks like the function that generates human readable durations has failed

```
Starting benchmark
Benchmark is running.
Benchmark is complete.

panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.humanizeDurationSeconds(0xc0cc60?)
        /go/src/github.com/wayfair-incubator/minigun/main.go:565 +0x19e
main.addSummaryToReport({0xc00200f380, 0x4, 0x4}, {0x895dc3, 0x16}, 0xc0cc60, {0x89c686, 0x21}, 0x0?)
        /go/src/github.com/wayfair-incubator/minigun/metrics.go:544 +0xaa
main.reportTextOld({0x1f4, 0x0, 0x0, {0xc00002a018, 0x15}, {0x7ffc6ba25b9e, 0x7}, 0x0, {0x0, 0x0}, ...}, ...)
        /go/src/github.com/wayfair-incubator/minigun/report.go:346 +0x191f
main.report({0x1f4, 0x0, 0x0, {0xc00002a018, 0x15}, {0x7ffc6ba25b9e, 0x7}, 0x0, {0x0, 0x0}, ...}, ...)
        /go/src/github.com/wayfair-incubator/minigun/report.go:72 +0xc5
main.main()
        /go/src/github.com/wayfair-incubator/minigun/main.go:808 +0x1aa5
```

## Expected Behaviour

Expected to not crash

## Actual Behaviour

Crashes when generating human readable report

## Affected Version

0.6.0

or `ghcr.io/wayfair-incubator/minigun:v0.6.0` to be more specific

## Steps to Reproduce

It's hard to reproduce, I've seen this only once. The parameters I used were:
```
# unlimited rps
-fire-target http://<SOME_IP>/
-workers 500
-fire-duration 1m
-send-timeout 10s
-random-body-size 100KB
```

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wayfair-incubator/minigun/blob/main/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by adidenko** [comment]
Yay! Can reproduce it like so:

```go
func TestHumanizeDurationSeconds(t *testing.T) {
	var seconds float64 = 60000
	var requests int = 10

	requestTime := humanizeDurationSeconds(seconds / float64(requests))
	if requestTime != "6000.00s" {
		t.Errorf("Wrong requestTime: %q", requestTime)
	}
}
```
